spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formflow
    hikari:
      maxLifetime: 540000 # 9 minutes (1 minute less than the default idleTimeout)
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB