spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formflow
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: ERROR
#flowsConfig: flows-config.yaml
#google_analytics: off
#google_analytics_id: CHANGEME
