name: flow1
flow:
  firstPage:
    nextScreens:
      - name: secondPage
  secondPage:
    nextScreens:
      - name: cardPage
  cardPage:
      nextScreens:
        - name: next
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
