name: flow1
flow:
  firstPage:
    nextScreens:
      - name: secondPage
  secondPage:
    nextScreens:
      - name: success
  success:
    nextScreens:
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
