name: ubi
flow:
  howThisWorks:
    nextScreens:
      - name: firstPage
  firstPage:
    nextScreens:
      - name: secondPage
        condition: applicantIsFemale
      - name: success
  secondPage:
    nextScreens:
      - name: success
  success:
    nextScreens:
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
