name: ubi
flow:
  howThisWorks:
    nextScreens:
      - name: eligibility
  eligibility:
    nextScreens:
      - name: housemates
  housemates:
    nextScreens:
      - name: housemateInfo
  housemateInfo:
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: success
  success:
    nextScreens:
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
