name: ubi
flow:
  howThisWorks:
    nextScreens:
      - name: eligibility
  eligibility:
    nextScreens:
      - name: housemates
  housemates:
    nextScreens:
      - name: housemateInfo
        condition: hasHousehold
      - name: income
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: success
  income:
    nextScreens:
      - name: housemateIncome
        condition: hasHousehold
  reportedAnnualHouseholdIncome:
    nextScreens:
      - name: AnnualHouseholdIncome
  success:
    nextScreens:
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
