name: ubi
flow:
  howThisWorks:
    nextScreens:
      - name: languagePreference
  languagePreference:
    nextScreens:
      - name: personalInfo
  personalInfo:
    nextScreens:
      - name: eligibility
  eligibility:
    nextScreens:
      - name: housemates
  housemates:
    nextScreens:
      - name: housemateInfo
        condition: hasHousehold
      - name: income
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: income
  householdDeleteConfirmation:
    nextScreens:
  income:
    nextScreens:
      - name: householdMemberIncome
        condition: hasHousehold
  householdMemberIncome:
    subflow: income
    nextScreens:
      - name: incomeTypes
  incomeTypes:
    subflow: income
    nextScreens:
      - name: incomeAmounts
  incomeAmounts:
    beforeSave: clearIncomeAmountsBeforeSaving
    subflow: income
    nextScreens:
      - name: annualHouseholdIncome
  annualHouseholdIncome:
    nextScreens:
  reportedAnnualHouseholdIncome:
    nextScreens:
      - name: AnnualHouseholdIncome
  success:
    nextScreens:
subflows:
  household:
    entryScreen: housemates
    iterationStartScreen: housemateInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdDeleteConfirmation
  income:
    entryScreen: income
    iterationStartScreen: householdMemberIncome
    reviewScreen: annualHouseholdIncome
    deleteConfirmationScreen: bar
---
name: flow2
flow:
  anotherFirstPage:
    nextScreens:
      - name: anotherSecondPage
  anotherSecondPage:
    nextScreens:
      - name: cardPage
  cardPage:
    nextScreens:
