inputs:
  firstName:
    name: firstName
    type: TEXT
  lastName:
    name: lastName
    type: TEXT
  testTextInput:
    name: testTextInput
    type: TEXT
#  testRadioInput:
#    name: testRadioInput
#    type: RADIO
#    options:
#      - value: RED
#      - value: BLUE
#      - value: GREEN

