flowName: flow1
flow:
  firstPage:
    nextPages:
      - pageName: secondPage
  secondPage:
    nextPages:
      - pageName: cardPage
  cardPage:
      nextPages:
        - pageName: next
---
flowName: flow2
flow:
  anotherFirstPage:
    nextPages:
      - pageName: anotherSecondPage
  anotherSecondPage:
    nextPages:
      - pageName: cardPage
  cardPage:
    nextPages:
